openapi: 3.0.0
info:
  title: Bank API - cliente
  version: 1.0.0
  description: API para la gestión de clientes

servers:
  - url: http://localhost:8081
    description: Servicio de clientes
  - url: http://localhost:8082
    description: Servicio de productos
  - url: http://localhost:8083
    description: Servicio de movimientos

tags:
  - name: client
    description: Servicios de los clientes
  - name: product
    description: Servicios de los productos
  - name: movement
    description: Servicios de los movimientos

paths:
  /api/v1/client:
    get:
      tags:
        - client
      summary: Obtener todos los clientes
      responses:
        "200":
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ClientDto"

    post:
      tags:
        - client
      summary: Crear un cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientDto"
      responses:
        "201":
          description: Cliente creado

  /api/v1/client/{id}:
    get:
      tags:
        - client
      summary: Obtener un cliente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientDto"
        "404":
          description: Cliente no encontrado

    put:
      tags:
        - client
      summary: Actualizar cliente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientDto"
      responses:
        "200":
          description: Cliente actualizado

    delete:
      tags:
        - client
      summary: Eliminar cliente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Cliente eliminado

  /api/v1/product:
    get:
      tags:
        - product
      summary: Obtener todos los productos
      responses:
        "200":
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductDto"

    post:
      tags:
        - product
      summary: Crear producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductDto"
      responses:
        "201":
          description: Producto creado

  /api/v1/product/{id}:
    get:
      tags:
        - product
      summary: Obtener un producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDto"
        "404":
          description: Producto no encontrado

    put:
      tags:
        - product
      summary: Actualizar producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductDto"
      responses:
        "200":
          description: Producto actualizado

    delete:
      tags:
        - product
      summary: Eliminar producto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Producto eliminado

  /api/v1/movement:
    get:
      tags:
        - movement
      summary: Obtener todos los movimientos
      responses:
        "200":
          description: Lista de movimientos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MovementDto"

    post:
      tags:
        - movement
      summary: Registrar movimiento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MovementDto"
      responses:
        "201":
          description: Movimiento registrado

  /api/v1/movement/{id}:
    get:
      tags:
        - movement
      summary: Obtener un movimiento por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Movimiento encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovementDto"
        "404":
          description: Movimiento no encontrado

components:
  schemas:
    ClientDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        dni:
          type: string
        type:
          type: string
          enum: [personal, empresarial]

    ProductDto:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum:
            [
              ahorro,
              cuenta_corriente,
              plazo_fijo,
              credito_personal,
              credito_empresarial,
              tarjeta_credito,
            ]
        maintenanceFee:
          type: number
        movementLimit:
          type: integer
          nullable: true

    MovementDto:
      type: object
      properties:
        id:
          type: string
        productId:
          type: string
        clientId:
          type: string
        type:
          type: string
          enum: [deposito, retiro]
        amount:
          type: number
        date:
          type: string
          format: date-time
