server:
  port: 8081

spring:
  application:
    name: client-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/client-database
  kafka:
    bootstrap-servers: localhost:9092


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true